### ISSUE TITLE
Rendering web page fails with Error: "could not set lazy property paddings in controls.input.BaseInput"

### ISSUE THREAD

**Issue by traysh** [pureqml/controls#14]
The following error occurs when padding is set on EmailInput:
qml initialization failed:  Error: "could not set lazy property paddings in controls.input.BaseInput"

This only happens after commit 49ab256fee9b21f335c3d427576b5358b865f17e "relaxed paddings creation". Reverting this commit fixes the problem.

Example code:
```
        EmailInput {
            width: 750;
            height: 100;

            border.width: 1;
            border.color: '#979797';
            backgroundColor: "white";
            font.pixelSize: 42;
            paddings: Paddings { left: 20; right: 20; }
            placeholder: PlaceHolder { text: qsTr('Enter your email'); }
        }
```

**Comment by whoozle** [comment]
Hello!
Thanks for reaching us out. 

Instead of `paddings: Paddings { left: 20; right: 20; }` try using `padding.left: 20; padding.right: 20;` 

Because we maintain 1:1 mapping between qml component and javascript object, we're trying to keep component footprint as low as possible. So normally we just lazily instantiate it on first get/set.

The same applies to placeholder.

Hope this helps
